plugins {
    id 'com.github.ben-manes.versions' version '0.52.0'
    id 'java'
    id 'application'
}

group = 'com.asteroid.duck'
version = '1.0.0'

mainClassName = 'com.asteroid.duck.velociwraptor.Main'

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // JMTE is our template engine
    implementation group: 'com.floreysoft', name: 'jmte', version: '7.0.3'
    // JSON API for parsing project.json
    implementation 'javax.json:javax.json-api:1.1.4'
    // JANSI makes the interactive console pretty colours
    implementation 'org.fusesource.jansi:jansi:2.4.1'
    // download, copy files etc.
    implementation group: 'commons-io', name: 'commons-io', version: '2.18.0'
    // command line parser
    implementation group: 'commons-cli', name: 'commons-cli', version: '1.9.0'
    implementation 'info.picocli:picocli:4.7.6'
    // logging
    implementation group: 'org.slf4j', name: 'slf4j-api', version: '2.0.6'
    // runtime JSON Lib
    implementation 'org.glassfish:javax.json:1.1.4'
    // logging for runtime
    implementation 'ch.qos.logback:logback-classic:1.5.16'


    // test dependencies...
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-all:2.0.2-beta'

    // min web server for tests
    testImplementation 'io.javalin:javalin:6.4.0'

}

// generate version number resource
ext.genOutputDir = file("$buildDir/generated-resources")
task generatePropInfo {
    ext.outputFile = file("$genOutputDir/project-info.properties")
    outputs.file(outputFile)
    doLast {
        outputFile.text = "version=${project.version}"
    }
}
sourceSets.main.output.dir genOutputDir, builtBy: generatePropInfo

task downloadTemplate {
    description "Downloads the latest version of the template from github"
    group "verification"
    doLast {
        def jar = new File(buildDir, "tmp/template.zip")
        jar.withOutputStream {
            out -> new URL("https://github.com/duckAsteroid/velociwraptor/archive/template.zip").withInputStream {
                from -> out << from
            }
        }
    }
}

task copyAndRenameZip(type: Copy) {
    group "verification"
    from zipTree("${buildDir}/tmp/template.zip")
    into "${buildDir}/explodedZip/"
}

task createTemplate(type: Zip) {
    description "Modifies the downloaded ZIP into a JAR"
    group "verification"
    destinationDirectory = file("${projectDir}/src/test/resources/com/asteroid/duck/velociwraptor")
    archiveFileName = "template.jar"
    from "${buildDir}/explodedZip/velociwraptor-template/"
}

task extractDistribution(type: Copy) {
    description 'Extracts the distribution ZIP into a temp dir; ready for InnoSetup to consume'
    group 'distribution'
    from(zipTree("${buildDir}/distributions/velociwraptor-${project.version}.zip"))
    into "${buildDir}/distributions/"
}

task innoSetup (type: Exec){
    description "Creates an installer using InnoSetup"
    group "distribution"
    workingDir 'src/main/inno-setup'
    commandLine "c:\\Program Files (x86)\\Inno Setup 6\\iscc.exe", 'velociwraptor.iss'
}

innoSetup.dependsOn extractDistribution
extractDistribution.dependsOn distZip
