plugins {
    id 'com.github.ben-manes.versions' version '0.53.0'
    id 'java'
    id 'application'
    id 'org.graalvm.buildtools.native' version '0.11.3'
}

group = 'com.asteroid.duck'
version = '1.0.0'

application {
    mainClass = 'com.asteroid.duck.velociwraptor.Main'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

// In your build.gradle (Groovy DSL)
tasks.named('test', Test) {
    // This line is often the culprit. Set it to false or remove it.
    failFast = false

    // Ensure all tests run, even if some tasks fail.
    ignoreFailures = true

    // OR just remove the failFast line if it exists.
}


repositories {
    mavenCentral()
}

dependencies {
    // JMTE is our template engine
    implementation group: 'com.floreysoft', name: 'jmte', version: '7.0.3'
    // Jackson for parsing project json
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'

    // JANSI makes the interactive console pretty colours
    implementation 'org.fusesource.jansi:jansi:2.4.2'
    // download, copy files etc.
    implementation group: 'commons-io', name: 'commons-io', version: '2.21.0'
    // command line parser
    implementation 'info.picocli:picocli:4.7.7'
    // logging
    implementation group: 'org.slf4j', name: 'slf4j-api', version: '2.1.0-alpha1'

    // logging for runtime
    implementation 'ch.qos.logback:logback-classic:1.5.21'


    // test dependencies...
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-all:2.0.2-beta'

    // min web server for tests
    testImplementation 'io.javalin:javalin:6.7.0'

}

// generate version number resource
ext.genOutputDir = file("$buildDir/generated-resources")
tasks.register('generatePropInfo') {
    ext.outputFile = file("$genOutputDir/project-info.properties")
    outputs.file(outputFile)
    doLast {
        outputFile.text = "version=${project.version}"
    }
}
sourceSets.main.output.dir genOutputDir, builtBy: generatePropInfo

tasks.register('downloadTemplate') {
    description "Downloads the latest version of the template from github"
    group "verification"
    doLast {
        def jar = new File(buildDir, "tmp/template.zip")
        jar.withOutputStream {
            out ->
                new URL("https://github.com/duckAsteroid/velociwraptor/archive/template.zip").withInputStream {
                    from -> out << from
                }
        }
    }
}

tasks.register('copyAndRenameZip', Copy) {
    group "verification"
    from zipTree("${buildDir}/tmp/template.zip")
    into "${buildDir}/explodedZip/"
}

tasks.register('createTemplate', Zip) {
    description "Modifies the downloaded ZIP into a JAR"
    group "verification"
    destinationDirectory = file("${projectDir}/src/test/resources/com/asteroid/duck/velociwraptor")
    archiveFileName = "template.jar"
    from "${buildDir}/explodedZip/velociwraptor-template/"
}