title: Velociwraptor
email: christopher.senior@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  About the Velociwraptor project
twitter_username: duckAsteroid
github_username:  duckAsteroid

# Build settings
theme: jekyll-theme-minimal
